#!/usr/bin/env bash

eval "$(~/bin/docopts -V - -h - : "$@" <<EOF

Usage:
  backup-apps-list [<destination>]

This will output to the console (or create a text file at DESTINATION
if specified) that has a list of all installed applications.

----
Version 0.1

EOF
)"


function title
{
    echo
	echo "$@"
	echo "$(echo "$@" | sed 's/./=/g')"
}

function cmd
{
    echo $@
    if which $1 >/dev/null; then
        echo
        $@
    fi
}

if [[ $OSTYPE =~ 'darwin' ]]; then
    title 'Installed OSX app store applications'
    cmd parse-osx-application-list

    title 'Brew OSX Applications'
    cmd brew list
fi

if [[ $OSTYPE =~ 'linux' ]]; then
    title 'Apt manualy installed'
    cmd comm -23 \
        <(apt-mark showmanual | sort -u) \
        <(gzip -dc /var/log/installer/initial-status.gz |
                 sed -n 's/^Package: //p' | sort -u) |
        sed '/\(linux-headers\|linux-image\)/d'
fi

title 'Python 2x packages'
cmd pip list --format=freeze

title 'Python 3x packages'
cmd pip3 list --format=freeze

title 'Npm packages'
cmd npm -g list -depth 0

title 'Emacs packages'
cmd find ~/.emacs.d/elpa/ -maxdepth 1 -type d -exec basename \{\} \;
