
# CRONTAB EXAMPLES
# 0  10,12,14,16,18  *  *  *  $HOME/bin/cyborg run >> $HOME/.cyborg/log
#
# # Run the remote backup immediately after first.
# 30  08,10,12,14,16,18  *  *  *  $HOME/bin/cyborg run >> $HOME/.cyborg/log;$HOME/bin/cyborg --name=borgbase run >> $HOME/.cyborg/log-borgbase


[nas]
destination: /home/sm/net1/backup/tux-backup/
source: /home/sm/, /etc
exclude: exclude-nas

[borgbase]
destination: s68qeh3g@s68qeh3g.repo.borgbase.com:repo
source: /home/sm/, /etc
exclude: exclude-cloud
passphrase: properly-embellish-unenvied-bronze-economy-elude-grub-cable-strung-derby

